### PR TITLE
Faster Faster

### PR DESCRIPTION
**Pull request by JUSTIVE**
no performance issue found except shaking kakaotalk instance

### CODE REVIEW

**Comment by blurfx** [comment]
I think we need to make sure there are no problems even in a low-end environment.

**Comment by JUSTIVE** [comment]
image

**Comment by blurfx** [comment]
NO. Field testing is required for performance issues

**Comment by blurfx** [comment]
> no performance issue found except shaking kakaotalk instance

I've just tested and it does not seem to be a problem with using KakaoTalkAdBlock.

**Pull request merged**
